version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_container
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db
    stdin_open: true
    tty: true
    user: "ec2-user"  # ec2-user でコンテナを実行
    working_dir: /home/ec2-user/environment  # 作業ディレクトリの設定

  db:
    image: mariadb:latest
    ports:
      - "3307:3306"
    container_name: "db_container"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:




